-- CREATE DATABASE CASTORES;

USE CASTORES;


CREATE TABLE ROLES_USUARIOS(
ID_ROL INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOMBRE_ROL VARCHAR(30) NOT NULL
)

CREATE TABLE USUARIOS(
ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(100) NOT NULL,
CORREO VARCHAR(50) NOT NULL,
CONTRASENA VARCHAR(25) NOT NULL,
ID_ROL INT NOT NULL,
ESTATUS BIT NOT NULL,
FOREIGN KEY (ID_ROL) REFERENCES ROLES_USUARIOS(ID_ROL)
);

CREATE TABLE PRODUCTOS(
ID_PRODUCTO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(30) NOT NULL,
CANTIDAD INT DEFAULT(0) NOT NULL,
ACTIVO BIT DEFAULT(1) NOT NULL
)

CREATE TABLE HISTORIAL(
ID_MOVIMIENTO BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
ID_USUARIO INT NOT NULL,
ID_PRODUCTO INT NOT NULL,
TIPO_MOVIMIENTO TINYINT NOT NULL,
CANTIDAD INT NOT NULL,
FECHA DATETIME DEFAULT(GETDATE()) NOT NULL,
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
)


INSERT INTO ROLES_USUARIOS(NOMBRE_ROL)
VALUES('ADMIN'),('ALMACENISTA')

INSERT INTO USUARIOS(NOMBRE,CORREO,CONTRASENA,ID_ROL,ESTATUS) 
VALUES
('ADMIN','admin@castores.com.mx','C45t0r35_2025',1,1),
('ALMACENISTA','almacenista@castores.com.mx','ALMACENISTA2025',2,1),
('USUARIO INACTIVO','almacenista_inactivo@castores.com.mx','123456',2,0)

INSERT INTO PRODUCTOS(NOMBRE,CANTIDAD)
VALUES('LAPTOP',15),('PC',20),('MOUSE',5),('TECLADO',25),('MONITOR',30)
